# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f595db879b4b29da97d7a2391c689378c3a879dad47aa28c30caf91f22e3d1e5c8232c7a2cee621e009c53205a7044d2b93dfad23b069c1aacde5e18086ac15e

test:
  secret_key_base: c2cb5b2dda6be0195d7d8ae601a81823432685997069a89537974f9f21ed9a4ece3058ab107630621cf9d652fa45c03237b200c59b0002e9102c3fa3313d6d32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
